language: node_js
node_js:
  - "12"
servisces:
  - docker

before_install:
  - yarn
script 
  - yarn build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t xzzlife/umi-demo:latest
  - docker push xzzlife/umi-demo:latest